### ISSUE TITLE
Trying to reach you to ask about HMAC issue

### ISSUE THREAD

**Issue by neu5** [chhornponleu/next-translate-app-dir-demo#1]
Hey, I'm trying to reach you to ask you if you managed to resolve this issue?
https://github.com/vercel/next.js/issues/34027

I'm having the very similar problem
https://github.com/vercel/next.js/issues/63629

You can answer to me via mail, which is public on my GH account
https://github.com/neu5

Cheers!

**Comment by chhornponleu** [comment]
@neu5 
Hey, Neu!
Just found out you were trying to reach me for the issue.

It was very old issue and I couldn't recall whether there was a solution or I gave up. But recently I'm on another project using `jose v5.x` with `nextjs 14`, node `18`, and it works well in dev and prod.

It's good if you could create a minimal reproducible repo so that I can help easily.

**Comment by neu5** [comment]
Hey @chhornponleu !
Thank you for answering me :)

I'm using `nextjs 14` with node `18`. At this point I made some workaround.
I'll get back to this issue after I'll resolve more important things.

Anyhow thank you for your answer.
